openapi: 3.2.0
info:
  title: Aptean Integration Platform Events API
  version: '1.0'
security:
- Bearer: []
tags:
- name: Events
paths:
  /v1/events:
    post:
      tags:
      - Events
      summary: Publish event from a specific tenant
      parameters:
      - name: x-aptean-product
        in: header
        description: Product ID for authorization.
        required: true
        schema:
          type: string
          format: uuid
      - name: x-aptean-tenant
        in: header
        description: Tenant ID for authorization.
        required: true
        schema:
          type: string
          format: uuid
      - name: x-aptean-apim
        in: header
        description: API key for authorization.
        schema:
          type: string
      requestBody:
        description: Event to publish with payload.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Requests.PublishEventRequest'
          text/json:
            schema:
              $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Requests.PublishEventRequest'
          application/*+json:
            schema:
              $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Requests.PublishEventRequest'
      responses:
        '201':
          description: Created
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
        '500':
          description: Internal Server Error
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipErrorResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipErrorResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipErrorResponse'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
      operationId: postV1Events
      x-operation-id-source: derived
  /v1/events/consumer-events/{consumerId}:
    get:
      tags:
      - Events
      summary: Get published events subscribed to by the specific tenant
      parameters:
      - name: consumerId
        in: path
        description: Tenant ID of the consumer.
        required: true
        schema:
          type: string
      - name: startDate
        in: query
        description: Optional start date.
        schema:
          type: string
          format: date-time
      - name: endDate
        in: query
        description: Optional end date.
        schema:
          type: string
          format: date-time
      - name: x-aptean-tenant
        in: header
        description: Tenant ID for authorization.
        schema:
          type: string
          format: uuid
      - name: x-aptean-product
        in: header
        description: Product ID for authorization.
        schema:
          type: string
          format: uuid
      - name: x-aptean-apim
        in: header
        description: API key for authorization.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
      operationId: getV1EventsConsumerEventsByConsumerId
      x-operation-id-source: derived
  /v1/events/{eventId}:
    get:
      tags:
      - Events
      summary: Get a specific event by its ID
      parameters:
      - name: eventId
        in: path
        description: Event ID.
        required: true
        schema:
          type: string
      - name: x-aptean-tenant
        in: header
        description: Tenant ID for authorization.
        schema:
          type: string
          format: uuid
      - name: x-aptean-product
        in: header
        description: Product ID for authorization.
        schema:
          type: string
          format: uuid
      - name: x-aptean-apim
        in: header
        description: API key for authorization.
        schema:
          type: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
        '400':
          description: Bad Request
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            application/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
            text/json:
              schema:
                $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse'
        '401':
          description: Unauthorized
          content:
            text/plain:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            application/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
            text/json:
              schema:
                $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
      operationId: getV1EventsByEventId
      x-operation-id-source: derived
components:
  schemas:
    Aptean.ATG.IntegrationPlatform.Api.Resources.Base.Owner:
      type: object
      properties:
        producerId:
          type: string
          description: Gets or sets producer id.
          format: uuid
      additionalProperties: false
      description: Representation of the owner model.
    Microsoft.AspNetCore.Mvc.ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    Aptean.ATG.IntegrationPlatform.Api.Resources.Requests.PublishEventRequest:
      required:
      - eventDefinitionType
      type: object
      properties:
        eventDefinitionType:
          minLength: 1
          type: string
          description: Gets or sets the event definition type.
        payload:
          type: object
          description: Gets or sets the payload.
      additionalProperties: false
      description: Publish Event Request.
    Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipWarningResponse:
      type: object
      properties:
        warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
          description: Gets or sets the collection of warnings for executed action.
      additionalProperties: false
      description: Warning AIP response.
    Aptean.ATG.IntegrationPlatform.Api.Resources.Event:
      type: object
      properties:
        id:
          type: string
          description: Gets or sets the unique identifier.
          format: uuid
        createdBy:
          type:
          - string
          - 'null'
          description: Gets the created by property.
        createdTimestamp:
          type: string
          description: Gets or sets timestamp that indicates when this document got created.
          format: date-time
        modifiedBy:
          type:
          - string
          - 'null'
          description: Gets the modified by property.
        modifiedTimestamp:
          type:
          - string
          - 'null'
          description: Gets or sets timestamp that indicates when this document got last modified.
          format: date-time
        payload:
          type: object
          description: The actual event Payload.
        correlationId:
          type:
          - string
          - 'null'
          description: CorrelationId from the processing pipeline.
        eventDefinitionId:
          type: string
          description: The event definition id of the event.
          format: uuid
        eventDefinitionType:
          type:
          - string
          - 'null'
          description: The event definition type.
        owner:
          $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Base.Owner'
        sourceTenant:
          type:
          - string
          - 'null'
          description: The source tenant.
        sentTimestamp:
          type:
          - string
          - 'null'
          description: Indicates when the event was sent.
          format: date-time
        failedTimestamp:
          type:
          - string
          - 'null'
          description: Indicates when the event was failed.
          format: date-time
        failureMessage:
          type:
          - string
          - 'null'
          description: Shows the failure message of this event.
      additionalProperties: false
      description: Representation of the Event model.
    ? Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipSuccessResponse_1_Aptean.ATG.IntegrationPlatform.Api.Resources.Event
    : type: object
      properties:
        warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
          description: Gets or sets the collection of warnings for executed action.
        items:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Aptean.ATG.IntegrationPlatform.Api.Resources.Event'
          description: The collection of items.
      additionalProperties: false
      description: 'Success typed AIP response.

        <typeparam name="TItem">Type of the item.</typeparam>'
    Aptean.ATG.IntegrationPlatform.Api.Resources.Responses.AipErrorResponse:
      type: object
      properties:
        warnings:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
          description: Gets or sets the collection of warnings for executed action.
        errors:
          type:
          - array
          - 'null'
          items:
            $ref: '#/components/schemas/Microsoft.AspNetCore.Mvc.ProblemDetails'
          description: Gets or sets the collection of errors for executed action.
      additionalProperties: false
      description: Error AIP response.
  securitySchemes:
    Bearer:
      type: http
      description: 'JWT Authorization header using the Bearer scheme. Example: "Authorization: Bearer {token}"'
      scheme: bearer
